print("Hello welcome to Comp 8")
name = input("what is your name?")
print (f" Hello{name} How are you feeling?Give one word emotion")
feeling = input ("")
print (f"i'm also feeling a bit {feeling}")
input ("")
print (f"Why are you feeling {feeling} ?")
feeling_reason = input ("") 
print ("oh that's nice i hope you can feel even better!")
input ("")
print ("My day has been going well")
input("")
print (" I have been very excited lately")
input ("")
print ("if you were wondering why I will tell you...")
input ("")
print("It's because i'm going to a soccer camp in Florida for break")
input("")
print("That's not even the only reason!")
input ("")
print ("My sisters birthday was yesterday! And this week is sprirt week and I am hype")